default_context:
  project_name: 'Reputation'
  project_slug: 'reputation.hivenetwork.online'
  domain_main: 'reputation.hivenetwork.online'
  domain_staging: 'staging.reputation.hivenetwork.online'
  docker_swarm_stack_name_main: 'reputation-hivenetwork-online'
  docker_swarm_stack_name_staging: 'staging-reputation-hivenetwork-online'
  secret_key: '1454ff2230592a3703bfc6dc9d4e06f43d06cbd63d10d372bfefa5f18b94f695'
  first_superuser: 'dev@hivenetwork.online'
  first_superuser_password: '308a92b5ee328a19f636e069a1ca153c09df2b256ae523a1ee75b25aabdb0356'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.reputation.hivenetwork.online", "https://staging.reputation.hivenetwork.online", "https://reputation.hivenetwork.online", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'dev@hivenetwork.online'
  postgres_password: '308a92b5ee328a19f636e069a1ca153c09df2b256ae523a1ee75b25aabdb0356'
  pgadmin_default_user: 'dev@hivenetwork.online'
  pgadmin_default_user_password: '308a92b5ee328a19f636e069a1ca153c09df2b256ae523a1ee75b25aabdb0356'
  traefik_constraint_tag: 'reputation.hivenetwork.online'
  traefik_constraint_tag_staging: 'staging.reputation.hivenetwork.online'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:308a92b5ee328a19f636e069a1ca153c09df2b256ae523a1ee75b25aabdb0356'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
