"""user_id is foreign key

Revision ID: 011b7cac841e
Revises: 0a94b1b24578
Create Date: 2020-10-13 09:16:08.178292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011b7cac841e'
down_revision = '0a94b1b24578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'commitment', 'user', ['deliverer'], ['id'])
    op.create_foreign_key(None, 'commitment', 'user', ['reporter'], ['id'])
    op.create_foreign_key(None, 'reputation', 'user', ['user_id'], ['id'])
    op.drop_column('reputation', 'full_name')
    op.create_foreign_key(None, 'transaction', 'user', ['deliverer'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.add_column('reputation', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reputation', type_='foreignkey')
    op.drop_constraint(None, 'commitment', type_='foreignkey')
    op.drop_constraint(None, 'commitment', type_='foreignkey')
    # ### end Alembic commands ###
