"""pk from user table in identity added to user table in repulation

Revision ID: 116c50c6f071
Revises: 5ecead3a5fd7
Create Date: 2020-11-18 01:09:47.626126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116c50c6f071'
down_revision = '5ecead3a5fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('memberships_user_id_fkey', 'memberships', type_='foreignkey')
    #op.create_foreign_key(None, 'memberships', 'user', ['user_id'], ['identity_user_id'])
    op.add_column('user', sa.Column('identity_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_identity_user_id'), 'user', ['identity_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_identity_user_id'), table_name='user')
    op.drop_column('user', 'identity_user_id')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key('memberships_user_id_fkey', 'memberships', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
