"""fix alembic issue

Revision ID: 1be0053f7edb
Revises: 116c50c6f071
Create Date: 2020-11-18 01:17:42.173256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be0053f7edb'
down_revision = '116c50c6f071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
