"""remove unused columns

Revision ID: 1d5a2984dc46
Revises: 57c0c9882262
Create Date: 2020-11-23 05:03:06.017583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5a2984dc46'
down_revision = '57c0c9882262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_commitment_id_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_deliverer_fkey', 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'commitment_id')
    op.drop_column('transaction', 'deliverer')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('transaction', sa.Column('deliverer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transaction', sa.Column('commitment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transaction_deliverer_fkey', 'transaction', 'user', ['deliverer'], ['identity_user_id'])
    op.create_foreign_key('transaction_commitment_id_fkey', 'transaction', 'commitment', ['commitment_id'], ['id'])
    # ### end Alembic commands ###
