"""is_active column no longer set to true by default

Revision ID: 3b1b709348f3
Revises: 1bf04c9b67fd
Create Date: 2020-11-17 06:46:46.286164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1b709348f3'
down_revision = '1bf04c9b67fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
