"""created_at column added to tx model

Revision ID: 57c0c9882262
Revises: 72f94264e8b5
Create Date: 2020-11-23 04:16:53.932378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c0c9882262'
down_revision = '72f94264e8b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'created_at')
    # ### end Alembic commands ###
