"""user fk

Revision ID: 58eec41ac36c
Revises: 5d2082fb8a41
Create Date: 2020-11-22 19:03:38.151455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58eec41ac36c'
down_revision = '5d2082fb8a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('commitment_deliverer_fkey', 'commitment', type_='foreignkey')
    op.drop_constraint('commitment_reporter_fkey', 'commitment', type_='foreignkey')
    op.create_foreign_key(None, 'commitment', 'user', ['reporter'], ['identity_user_id'])
    op.create_foreign_key(None, 'commitment', 'user', ['deliverer'], ['identity_user_id'])
    op.drop_constraint('reputation_user_id_fkey', 'reputation', type_='foreignkey')
    op.create_foreign_key(None, 'reputation', 'user', ['user_id'], ['identity_user_id'])
    op.drop_constraint('transaction_deliverer_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'user', ['deliverer'], ['identity_user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_deliverer_fkey', 'transaction', 'user', ['deliverer'], ['id'])
    op.drop_constraint(None, 'reputation', type_='foreignkey')
    op.create_foreign_key('reputation_user_id_fkey', 'reputation', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'commitment', type_='foreignkey')
    op.drop_constraint(None, 'commitment', type_='foreignkey')
    op.create_foreign_key('commitment_reporter_fkey', 'commitment', 'user', ['reporter'], ['id'])
    op.create_foreign_key('commitment_deliverer_fkey', 'commitment', 'user', ['deliverer'], ['id'])
    # ### end Alembic commands ###
