"""plan_id added to commitment and transaction models

Revision ID: 5d2082fb8a41
Revises: ec372b070096
Create Date: 2020-11-19 07:06:27.832293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2082fb8a41'
down_revision = 'ec372b070096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commitment', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_commitment_plan_id'), 'commitment', ['plan_id'], unique=False)
    op.add_column('transaction', sa.Column('plan_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'plan_id')
    op.drop_index(op.f('ix_commitment_plan_id'), table_name='commitment')
    op.drop_column('commitment', 'plan_id')
    # ### end Alembic commands ###
