"""group reputation table added

Revision ID: 6a12e66acc5b
Revises: 7902afe95fc3
Create Date: 2020-12-01 13:06:07.481267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a12e66acc5b'
down_revision = '7902afe95fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupreputation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coop_id', sa.Integer(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groupreputation_id'), 'groupreputation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groupreputation_id'), table_name='groupreputation')
    op.drop_table('groupreputation')
    # ### end Alembic commands ###
