""" identity_user_id constraint added in membership table

Revision ID: ec372b070096
Revises: 1be0053f7edb
Create Date: 2020-11-18 01:23:50.051377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec372b070096'
down_revision = '1be0053f7edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_foreign_key(None, 'memberships', 'user', ['user_id'], ['identity_user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    # ### end Alembic commands ###
